
2013-10-05 17:11:42,870 - root - ERROR - Cannot connect to MySQL on localhost
Traceback (most recent call last):
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/torndb.py", line 91, in __init__
    self.reconnect()
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/torndb.py", line 108, in reconnect
    self._db = MySQLdb.connect(**self._db_args)
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
2013-10-05 17:11:42,879 - root - INFO - BeRoads webserver listening on 9000
2013-10-05 18:03:46,477 - root - ERROR - 
Traceback (most recent call last):
  File "main_2.py", line 1407, in <module>
    app = Application()
  File "main_2.py", line 238, in __init__
    if self.twitter_bots[language].VerifyCredentials() is None:
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/twitter.py", line 4165, in VerifyCredentials
    json = self._FetchUrl(url, no_cache=True)
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/twitter.py", line 4519, in _FetchUrl
    response = opener.open(url, encoded_post_data)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1174, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1161, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib64/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
2013-10-05 18:03:56,997 - root - ERROR - 
Traceback (most recent call last):
  File "main_2.py", line 1408, in <module>
    app = Application()
  File "main_2.py", line 239, in __init__
    if self.twitter_bots[language].VerifyCredentials() is None:
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/twitter.py", line 4165, in VerifyCredentials
    json = self._FetchUrl(url, no_cache=True)
  File "/var/www/html/beroads/dashboard/dashboard/lib/python2.7/site-packages/twitter.py", line 4519, in _FetchUrl
    response = opener.open(url, encoded_post_data)
  File "/usr/lib64/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1174, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1161, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib64/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
